name: BiomeFinder
version: "${projectVersion}"
main: com.github.siroshun09.biomefinder.BiomeFinderPlugin
author: Siroshun09
api-version: "1.20"
folia-supported: true
commands:
  findbiomes:
    aliases:
     - fb
  generateseed:
    aliases:
     - gs
